"""added username

Revision ID: 60af0e163c02
Revises: 68b211f6e097
Create Date: 2023-02-10 19:09:20.844649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60af0e163c02'
down_revision = '68b211f6e097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
